### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4.6
  description: Microsoft Application Virtualization 4.6 керується фіксованою політикою життєвого циклу.
  ms.date: 09/01/2020
  keywords: for Remote Desktop Services,for Windows Desktops,Sequencer
  ms.openlocfilehash: e7ee52090b6e77209d2cc75b5862c21dfe4fe3dd
  ms.sourcegitcommit: af46dd09ccdabd80dcc49d2cd930cefa0b1ab8a6
  ms.translationtype: HT
  ms.contentlocale: uk-UA
  ms.lasthandoff: 09/01/2020
  ms.locfileid: "935582"
name: Microsoft Application Virtualization 4.6
summary: >+
  Microsoft Application Virtualization 4.6 керується [фіксованою](/lifecycle/policies/fixed) політикою життєвого циклу.


  Це стосується таких випусків: для служб віддалених робочих столів, Windows для настільних ПК

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Посилання \n* [Інформація про виріб та міграцію](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Вказівки щодо міграції](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)\n* [Політика пакетів оновлень](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Оскільки клієнт App-V 4.6 використовує сервер App-V 4.5, підтримка сервера App-V 4.5 буде продовжуватися відповідно до дат життєвого циклу App-V 4.6 у разі його використання з підтримуваним клієнтом App-V 4.6.\n\n## <a name=\"editions\"></a>Версії \n* для служб віддалених робочих столів\n* для Windows для настільних ПК\n* Sequencer"
