### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4.5
  description: Microsoft Application Virtualization 4.5 керується фіксованою політикою життєвого циклу.
  ms.date: 09/01/2020
  keywords: for Terminal Services,for Windows Desktops
  ms.openlocfilehash: 2d8a71caede673b568a595526f4e1c9ce41a1778
  ms.sourcegitcommit: af46dd09ccdabd80dcc49d2cd930cefa0b1ab8a6
  ms.translationtype: HT
  ms.contentlocale: uk-UA
  ms.lasthandoff: 09/01/2020
  ms.locfileid: "935656"
name: Microsoft Application Virtualization 4.5
summary: >
  Microsoft Application Virtualization 4.5 керується [фіксованою](/lifecycle/policies/fixed) політикою життєвого циклу.


  Це стосується наступних випусків: для служб терміналів, для настільних ПК під управлінням Windows


  > [!IMPORTANT]

  > Підтримка цього продукту закінчилась. Перегляньте інструкції з міграції, наведені нижче.
products:
- windows
policyType: fixed
supportDates:
  start: 11/23/2008
  end: 01/14/2014
  extendedEnd: 01/08/2019
releases:
- version: Service Pack 2
  startDate: 08/15/2010
  endDate: 01/08/2019
- version: Service Pack 1
  startDate: 12/13/2009
  endDate: 10/11/2011
- version: Original Release
  startDate: 11/23/2008
  endDate: 01/11/2011
content: "\n## <a name=\"links\"></a>Посилання \n* [Вказівки щодо міграції](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Політика пакетів оновлень](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Оскільки клієнт App-V 4.6 використовує сервер App-V 4.5, підтримка сервера App-V 4.5 буде продовжуватися відповідно до дат життєвого циклу App-V 4.6 у разі його використання з підтримуваним клієнтом App-V 4.6.\n\n## <a name=\"editions\"></a>Версії \n* для служб терміналів\n* для Windows для настільних ПК"
