### YamlMime:Lifecycle
metadata:
  title: Диспетчер конфігурацій Microsoft System Center (LTSB-Version 1606)
  description: Диспетчер конфігурації Microsoft System Center (LTSB-Version 1606) наслідує політику фіксованого життєвого циклу.
  ms.date: 08/20/2020
  ms.openlocfilehash: 606034d7f3694f3e06a47bdc5e1a45561102c238
  ms.sourcegitcommit: f5095aa6fc41dcc71c883cae08719b5b6bf9585c
  ms.translationtype: MT
  ms.contentlocale: uk-UA
  ms.lasthandoff: 08/20/2020
  ms.locfileid: "906028"
name: Диспетчер конфігурацій Microsoft System Center (LTSB-Version 1606)
summary: >+
  Диспетчер конфігурації Microsoft System Center (LTSB-Version 1606) наслідує політику [фіксованого](/lifecycle/policies/fixed) життєвого циклу.


products:
- m365
policyType: fixed
supportDates:
  start: 10/12/2016
  end: 10/12/2021
  extendedEnd: 01/12/2027
releases:
- version: Original Release
  startDate: 10/12/2016
  endDate: 01/12/2027
content: "\n## <a name=\"links\"></a>Посилання \n* [Відомості про обслуговування та підтримку](/sccm/core/understand/learn-more-editions)"
